{% set python_min = python_min|default("3.6") %}
{% set name = "sscws" %}
{% set version = "2.4.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/sscws-{{ version }}.tar.gz
  sha256: 13555853d51ce8ca9b065b22f190e17360cd720795b5bfcb4f9679442200a345

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >={{ python_min }}.*
    - pip
    - setuptools
  run:
    - python >={{ python_min }}.*
    - python-dateutil >=2.8.0
    - requests >=2.20
    - numpy >=1.19.4
    - urllib3 >=1.26.16

test:
  imports:
    - sscws
  commands:
    - pip check
  requires:
    - python >={{ python_min }}
    - pip

about:
  home: https://sscweb.gsfc.nasa.gov/WebServices/REST
  summary: NASA's Satellite Situation Center Web Service Client Library
  license: NOSL
  license_file: NASA_Open_Source_Agreement_1.3.txt

extra:
  recipe-maintainers:
    - candeynasa
    - ericthewizard
    - berniegsfc
