{% set name = "sscws" %}
{% set version = "2.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/sscws-{{ version }}.tar.gz
  sha256: ef8fd69de106fecd2e466e8baf060182a191404e37da0f990661f64de2744b03

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - python-dateutil >=2.8.0
    - requests >=2.20
    - numpy >=1.19.4
    - urllib3 >=1.26.16

test:
  imports:
    - sscws
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://sscweb.gsfc.nasa.gov/WebServices/REST
  summary: NASA's Satellite Situation Center Web Service Client Library
  license: NOSL
  license_file: NASA_Open_Source_Agreement_1.3.txt

extra:
  recipe-maintainers:
    - ericthewizard
    - berniegsfc
